server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/asdasd?useSSL=false&serverTimezone=UTC
    username: root
    password: 123
  data:
    redis:
      host: 192.168.102.128
      port: 6379
      password: 123123
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s

springdoc:
  swagger-ui:
    path: /swagger-ui.html
knife4j:
  enable: true
  setting:
    language: zh_cn
lucky:
    jwt:
      # 设置jwt签名加密时使用的秘钥
      #
      #admin-secret-key: itcast
      # 设置jwt过期时间
      #admin-ttl: 7200000
      # 设置前端传递过来的令牌名称
      #admin-token-name: token
      user-secret-key: myUltraSecureJWTSecretKeyForUser123456
      user-ttl: 7200000
      user-token-name: token


mybatis-plus:
  type-aliases-package: com.example.demo.entity # 别名扫描包
redis:
  host:
